### ISSUE TITLE
Support multiple submit buttons with different actions/intents

### ISSUE THREAD

**Issue by mjbp** [stormid/storm-validate#16]
Context: 
A form can have two (or more) distinct submission actions (e.g., 'save' and 'save and continue'). Currently, post-validation this library invokes form.submit(), triggering the default submit action of the form. There is currently no way to distinguish the divergent intent.

We do not submit asynchronously or compose/change the form data in-flight - I'd argue that is outwith the concerns this library - we hand over all control once the form.submit() is invoked. We're attempting to support HTML5 definitions for all validation and form behaviours (as well as .net mvc unobtusive validation).

Solutions:
First reflections suggest two (reasonable-ish) candidate solutions for this library:

1. Add support for two submit buttons with the same name and different values.
Once validation is passed the document.activeElement is checked, if it is a button/input[type=submit] and has name and value attributes then the name/value is appended to the form  in a hidden field, the name/value describing the intent is handled server-side.

In the case of another library performing asychronous submission the new field would persist in the DOM so we would have check for it's existence and recycle it in our pre-submit function. 

2. Add support for a formaction (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#attr-formaction) attribute on a submit button/input to override the action attribute of the form itself. 

Once validation is passed the document.activeElement is checked for a formaction property, if present the action attribute of the form is mutated to the new intended formaction. Alternatively, a button with a formaction attribute could mutate the form action prior to validation on each click/pointer event.

In the case of another library performing asychronous submission the new action would persist so we would need to check/track the change in the pre-submit function - e.g., set a data-default-action attribute on the form when we mutate the action, and check for it on each submission.

**Comment by gjstockham** [comment]
For reference: https://laracasts.com/discuss/channels/laravel/submit-button-value-not-available-in-request
